name: career_advisor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.5  # Ready for backend integration later

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/landing_bg.jpg
    - assets/profile_bg.jpg
    - assets/gn_interest_bg.jpg
    - assets/description_bg.jpg
